#!/bin/bash

#PBS -N u_train

#PBS -q phi-n1h72

#PBS -l nodes=1:ppn=1

#PBS -l walltime=71:59:59

#PBS -o /home/mamendez/Pytorch-UNet/nuevo_approach/prueba.txt

module load opencv/2.4.13.3

module load cuda/8.0.61

module load cudnn-8/6.0.21

module load intelpython/3.5

module load hdf5/1.10.0-patch1

module load tiff/3.9.7

cd $PBS_O_WORKDIR

python /home/mamendez/Pytorch-UNet/nuevo_approach/data.py
python /home/mamendez/Pytorch-UNet/nuevo_approach/unet.py